### PR TITLE
Update specs to require SDWebImage 4.0.x to resolve SDWebImage out of…

### PR DESCRIPTION
**Pull request by jin0112**
We just encounter issue when integrate SDWebImage, which conflict version with your version required.

### CODE REVIEW

**Comment by Wenzhi** [comment]
Hey @jin0112,

Thanks for the pull request! However, we would also need to update our SDK to support SDWebImage 4.0, so just changing the .podspec file isn't enough.

We've been watching SDWebImage and waiting for the stable version of 4.0. When it's released, we will update our SDK to adopt the new version as soon as possible.  I'm going to close your pull request for now, and we will inform you when the new release comes out.

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
Hey @jin0112,

If you are in an urgent need of SDWebImage 4.0 support with Appboy SDK, we can release a beta version of the SDK for it. Would that solve your issue? If that's what you prefer, could you let us know how you integrate Appboy(Cocoapods/Carthage/manual integration, etc)? 

Thanks,
Wenzhi

**Comment by jin0112** [comment]
Hi Wenzhi,
Thanks for your respond, we're using your Appboy SDK via Cocoapods. If you could, pls support a beta version support latest SDWebImage, thanks a lot.

**Comment by Wenzhi** [comment]
Hey @jin0112, 

Our beta support development is blocked by an active [GIF issue](https://github.com/rs/SDWebImage/issues/1700) in SDWebImage 4.0. As our default UI supports GIF, we cannot bypass this issue, unfortunately. We will be watching for a fix from SDWebImage and update as soon as we can.

Do you use Appboy's default in-app message and/or news feed page? 

Thanks,
Wenzhi

**Pull request closed without merging**
